### ISSUE TITLE
libsysstat in LXQt 1.1.0

### ISSUE THREAD

**Issue by tsujan** [lxqt/libsysstat#46]
libsysstat hasn't changed at all since LXQt 1.0.0, and so, I think there's no need to bump its version artificially.

Is there any objection to using libsysstat-0.4.6 in LXQt 1.1.0?

**Comment by palinek** [comment]
I would also vote for not releasing, when there are no changes.

**Comment by tsujan** [comment]
@palinek 
This also happens in the case of `lxqt-qtplugin`: no commit since the last release, simply because no commit was needed.

However, the version of `lxqt-qtplugin` is that of LXQt. Should I make an exception for it and bump its version as well as its dependencies?
